export const mockBlogs = [
  {
    createdAt: '2022-06-21',
    id: 'micro-generator-plop',
    title: 'micro generator PLOP 란?',
    url: '/post/micro-generator-plop',
    published: true,
    isExternal: false,
  },
  {
    createdAt: '2018-07-08',
    id: 'react-prod-staging-dev-환경-설정하기',
    title: 'React prod, staging, dev 환경 설정하기',
    url: '',
    published: false,
    isExternal: false,
  },
  {
    createdAt: '2018-04-04',
    id: 'files-are-imported-from-their-absolute-paths-instead-of-their-relative-paths',
    title: 'React 상대경로 -> 절대경로 변경',
    url: '/post/files-are-imported-from-their-absolute-paths-instead-of-their-relative-paths',
    published: true,
    isExternal: false,
  },
  {
    createdAt: '2018-03-24',
    id: 'async-generator',
    title: 'Async Generator And Redux Saga',
    url: '/post/async-generator',
    published: false,
    isExternal: false,
  },
  {
    createdAt: '2018-03-23',
    id: 'list-map',
    title: 'list-map',
    url: '/post/list-map',
    published: false,
    isExternal: false,
  },
  {
    createdAt: '2018-03-23',
    id: 'oop-fp-pp',
    title: 'oop-ffp-pp',
    url: '/post/oop-ffp-pp',
    published: false,
    isExternal: false,
  },
  {
    createdAt: '2018-03-15',
    id: 'ui-ux',
    title: 'ui-ux',
    url: '/post/ui-ux',
    published: false,
    isExternal: false,
  },
  {
    createdAt: '2018-03-13',
    id: 'proxy-decorator-pattern',
    title: 'Proxy Decorator Pattern',
    url: '/post/proxy-decorator-pattern',
    published: false,
    isExternal: false,
  },
  {
    createdAt: '2018-03-12',
    id: 'debounce-throttle',
    title: 'React Debounce and Throttle',
    url: '/post/react-debounce-and-throttle',
    published: false,
    isExternal: false,
  },
  {
    createdAt: '2018-03-11',
    id: 'function-compare-code',
    title: 'React For pure function compare',
    url: '/post/function-compare-code',
    published: false,
    isExternal: false,
  },
  {
    createdAt: '2018-03-09',
    id: 'typeorm-like-jpa',
    title: 'Typeorm like jpa',
    url: '/post/typeorm-like-jpa',
    published: false,
    isExternal: false,
  },
  {
    createdAt: '2018-03-08',
    id: 'react-facc-hoc',
    title: 'Function as Child Component And High Order Component',
    url: '/post/react-facc-hoc',
    published: true,
    isExternal: false,
  },
  {
    createdAt: '2018-02-25',
    id: 'react-environment',
    title: 'React Custom Environment',
    url: '/post/react-environment',
    published: true,
    isExternal: false,
  },
  {
    createdAt: '2018-01-22T05:24:36.000Z',
    id: 'https://cultist-tp.tistory.com/264',
    title: 'Scroll Down 화면 만들기',
    url: 'https://cultist-tp.tistory.com/entry/Scroll-Down-%ED%99%94%EB%A9%B4-%EB%A7%8C%EB%93%A4%EA%B8%B0',
    published: true,
    isExternal: true,
  },
  {
    createdAt: '2017-10-15T10:33:34.000Z',
    id: 'https://cultist-tp.tistory.com/263',
    title: '푸터 하단 고정 시키기',
    url: 'https://cultist-tp.tistory.com/entry/%ED%91%B8%ED%84%B0-%ED%95%98%EB%8B%A8-%EA%B3%A0%EC%A0%95-%EC%8B%9C%ED%82%A4%EA%B8%B0',
    published: true,
    isExternal: true,
  },
  {
    createdAt: '2017-10-15T09:48:29.000Z',
    id: 'https://cultist-tp.tistory.com/262',
    title: 'IOS Safari minimal-ui 적용기',
    url: 'https://cultist-tp.tistory.com/entry/IOS-Safari-minimalui-%EC%A0%81%EC%9A%A9%EA%B8%B0',
    published: true,
    isExternal: true,
  },
  {
    createdAt: '2017-09-01T08:33:46.000Z',
    id: 'https://cultist-tp.tistory.com/261',
    title: 'Node 버전 관리',
    url: 'https://cultist-tp.tistory.com/entry/Node-%EB%B2%84%EC%A0%84-%EA%B4%80%EB%A6%AC',
    published: true,
    isExternal: true,
  },
  {
    createdAt: '2017-08-16T21:11:29.000Z',
    id: 'https://cultist-tp.tistory.com/260',
    title: 'React Reducer 관리',
    url: 'https://cultist-tp.tistory.com/entry/React-Reducer-%EA%B4%80%EB%A6%AC',
    published: true,
    isExternal: true,
  },
  {
    createdAt: '2017-07-28T12:29:16.000Z',
    id: 'https://cultist-tp.tistory.com/259',
    title: 'React Heroku 초기 세팅.',
    url: 'https://cultist-tp.tistory.com/entry/React-Heroku-%EC%B4%88%EA%B8%B0-%EC%84%B8%ED%8C%85',
    published: true,
    isExternal: true,
  },
  {
    createdAt: '2017-06-12T09:00:21.000Z',
    id: 'https://cultist-tp.tistory.com/258',
    title: 'SOLID',
    url: 'https://cultist-tp.tistory.com/entry/SOLID',
    published: true,
    isExternal: true,
  },
  {
    createdAt: '2017-06-12T07:45:19.000Z',
    id: 'https://cultist-tp.tistory.com/257',
    title: '소나 버그 잡기',
    url: 'https://cultist-tp.tistory.com/entry/%EC%86%8C%EB%82%98-%EB%B2%84%EA%B7%B8-%EC%9E%A1%EA%B8%B0',
    published: true,
    isExternal: true,
  },
  {
    createdAt: '2017-06-12T07:41:35.000Z',
    id: 'https://cultist-tp.tistory.com/256',
    title: 'QueryDSL 문서',
    url: 'https://cultist-tp.tistory.com/entry/QueryDSL-%EB%AC%B8%EC%84%9C',
    published: true,
    isExternal: true,
  },
  {
    createdAt: '2017-06-12T07:38:13.000Z',
    id: 'https://cultist-tp.tistory.com/255',
    title: '엑셀 SQL 구문 추출',
    url: 'https://cultist-tp.tistory.com/entry/%EC%97%91%EC%85%80-SQL-%EA%B5%AC%EB%AC%B8-%EC%B6%94%EC%B6%9C',
    published: true,
    isExternal: true,
  },
];
