import {
  portfolioCompetitionImages,
  portfolioHouseImages,
  portfolioIntersectionImages,
  portfolioSkhualarmImages,
  portfolioSofthomeImages,
} from '@bbl-nx/images';

export const companyPortfolios = [
  {
    id: 'Naver',
    name: 'Naver',
    period: '2022.10 - ',
    githubRepoName: [],
    skills: [
      'react',
      'recoil',
      'nextjs',
      'typescript',
      'storybook',
      'i18next',
    ],
    summary: `네이버 쇼핑 라이브`,
    githubUrl: '',
    homeUrl: 'https://shoppinglive.naver.com/home/',
    googleStoreUrl: '',
    appStoreUrl: '',
    images: [],
  },
  {
    id: 'Henesis',
    name: 'Henesis',
    period: '2020.5 - 2022.5',
    githubRepoName: [],
    skills: [
      'react',
      'mobx-state-tree',
      'mobx',
      'nextjs',
      'gatsby',
      'emotion',
      'typescript',
      'storybook',
      'material-ui',
      'i18next',
    ],
    summary: `국내 주요 은행, 가상자산 거래소, 핀테크 회사, 가상자산 
수탁업체가 Henesis로 가상자산 관리하는 서비스`,
    githubUrl: '',
    linkUrl: 'https://henesis.io/',
    homeUrl: 'https://app.wallet.henesis.io/account/login',
    googleStoreUrl: '',
    appStoreUrl: '',
    images: [],
  },
  {
    id: 'Koda',
    name: 'KODA',
    period: '2021.4 - 2021.10',
    githubRepoName: [],
    skills: [
      'react',
      'mobx state tree',
      'mobx',
      'nextjs',
      'styled-components',
      'typescript',
      'storybook',
      'material-ui',
      'openapi-generator',
    ],
    summary: `비트코인 수탁 등 법인·기관 투자자를 위한 
디지털 자산 수탁 원스탑 서비스`,
    githubUrl: '',
    linkUrl: 'https://kodax.com/',
    homeUrl: 'https://app.kodax.com/account/login',
    googleStoreUrl: '',
    appStoreUrl: '',
    images: [],
  },
  {
    id: 'FITSME',
    name: 'FITSME',
    period: '2019.4 - 2020.1',
    githubRepoName: [],
    skills: [
      'react native',
      'mobx-state-tree',
      'mobx',
      'react-native-navigation-v2',
      'styled components',
      'typescript',
      'storybook',
      'graphql',
      'firebase',
    ],
    summary: '나에게 맞는, 더 나은 뷰티라이프',
    githubUrl: '',
    homeUrl: 'https://fitsme.kr/',
    googleStoreUrl:
      'https://play.google.com/store/apps/details?id=kr.fitsme.app',
    appStoreUrl: 'https://apps.apple.com/kr/app/id1466041001',
    images: [],
  },
  {
    id: 'HAECHI Website',
    name: 'HAECHI Website',
    period: '2019.6 - 2019.6',
    githubRepoName: [],
    skills: [
      'react',
      'gatsby',
      'styled-components',
      'typescript',
      'storybook',
      '18next',
    ],
    summary: 'haechi website',
    githubUrl: '',
    homeUrl: 'https://haechi.io/',
    googleStoreUrl: '',
    appStoreUrl: '',
    images: [],
  },
  {
    id: 'COSMEE',
    name: 'COSMEE',
    period: '2018.4 - 2019.3',
    githubRepoName: [],
    skills: [
      'react-native',
      'mobx-state-tree',
      'mobx',
      'react-native-navigation-v2',
      'styled-components',
      'antd',
      'typescript',
      'storybook',
      'appcenter',
    ],
    summary: '블록체인 보상을 통한 뷰티 커뮤니티',
    githubUrl: '',
    linkUrl:
      'https://medium.com/@Cosmochain/cosmee-app-now-available-on-google-play-store-f80149a2fa4c',
    images: [],
  },
  {
    id: 'buxi',
    name: 'Buxi',
    period: '2017.8 - 2017.11',
    githubRepoName: [],
    skills: [
      'react',
      'styled-components',
      'nodejs',
      'redux',
      'redux-saga',
      'webpack',
      'storybook',
    ],
    summary:
      '같은 목적지를 오가는 분들이 원하는 시간대에 함께 쓰는 새로운 카셰어링',
    githubUrl: '',
    homeUrl: 'https://www.buxikorea.com/',
    images: [],
  },
  {
    id: 'coupang',
    name: 'Coupang Account System',
    period: '2015.6 - 2017.7',
    githubRepoName: [],
    skills: [
      'react',
      'jquery',
      'underscore',
      'requrejs',
      'handlebars',
      'spring-framework',
    ],
    summary: '쿠팡 회계 시스템',
    githubUrl: '',
    linkUrl: '',
    images: [],
  },
  {
    id: 'team42',
    name: 'Team42',
    period: '',
    githubRepoName: [],
    skills: ['bootstrap', 'jQuery', 'velocity', 'lessjs'],
    summary: 'Team42 홈페이지',
    githubUrl: '',
    linkUrl: 'http://team42.net/',
    images: [],
  },
];

export const personalPortforlios = [
  {
    id: 'bbl',
    name: 'BoBeen Lee',
    period: 'sometimes',
    githubRepoName: ['bbl', 'bbl-nx', 'bbl-nextjs'],
    skills: [
      'react',
      'xstate',
      'nextjs',
      'nx.dev',
      'tailwind',
      'styled-components',
      'typescript',
      'storybook',
    ],
    summary: '나의 기록용, 블로그겸 홈페이지',
    githubUrl: 'https://github.com/BoBeenLee/bbl-nx',
    storybookUrl: 'https://62e8cb96780e4059ce3a88b5-zcknntuzly.chromatic.com/',
    homeUrl: 'https://bbl-nx.vercel.app/',
    images: [],
  },
  {
    id: 'skhualarm',
    name: 'Skhualarm',
    period: '',
    githubRepoName: [],
    skills: [
      'android',
      'facebook-Graph-API',
      'Picasso',
      'spring-framework',
      'myBatis',
      'jsoup',
      'quartz',
      'mariaDB',
    ],
    summary: 'Sungkonghoe University Alarm App',
    githubUrl: 'https://github.com/BoBeenLee/SkhuApp',
    homeUrl:
      'https://play.google.com/store/apps/details?id=com.skhu.bobinlee.skhuapp&hl=ko',
    images: Object.values(portfolioSkhualarmImages),
  },
];

export const teamPortfolios = [
  {
    id: 'onesecondmusicgame',
    name: 'onesecondmusicgame',
    period: '~ 2021.10.06',
    githubRepoName: [],
    skills: [
      'react',
      'react-native',
      'gatsby',
      'mobx-state-tree',
      'styled-components',
      'typescript',
      'storybook',
    ],
    summary: '1초 음악 맞추기 게임',
    githubUrl: '',
    storybookUrl: 'http://onesecondmusicgame.surge.sh/',
    homeUrl: '',
    appStoreUrl:
      'https://apps.apple.com/kr/app/%EC%95%8C%EC%8F%AD%EB%8B%AC%EC%8F%AD/id1493107650',
    googleStoreUrl:
      'https://play.google.com/store/apps/details?id=kr.nexters.onesecondmusicgame',
    images: [],
  },
  {
    id: 'inhousekitchen',
    name: 'Inhousekitchen',
    period: '',
    githubRepoName: [],
    skills: [
      'react-native',
      'nativebase',
      'expo',
      'redux-offline',
      'redux',
      'redux-saga',
      'storybook',
    ],
    summary: '셰프와 게스트 연결해주는 서비스',
    githubUrl: 'https://github.com/Nexters/inhousekitchen',
    homeUrl: '',
    images: Object.values(portfolioHouseImages),
  },
  {
    id: 'flass',
    name: 'Flass',
    period: '',
    githubRepoName: ['flass'],
    skills: [
      'react',
      'react-router',
      'mocha',
      'redux',
      'material-ui',
      'webpack',
      'sass',
      'rails',
    ],
    summary: 'Site For Flipped Learning',
    githubUrl: 'https://github.com/Nexters/flass',
    homeUrl: 'http://flass.me',
    images: [],
  },
  {
    id: 'onepage',
    name: 'Onepage',
    period: '',
    githubRepoName: [],
    skills: [
      'android',
      'retrofit2',
      'butterknife',
      'spring-boot',
      'queryDSL',
      'swaggerUI',
      'mockito',
      'mysql',
    ],
    summary: '위치기반 익명 SNS',
    githubUrl: 'https://github.com/OnePageAndroid',
    homeUrl:
      'https://play.google.com/store/apps/details?id=kr.nexters.onepage&hl=ko',
    images: [],
  },
  {
    id: 'intersection',
    name: 'Intersection',
    period: '',
    githubRepoName: [],
    skills: [
      'android',
      'material-design',
      'spring-framework',
      'hibernate',
      'postgreSQL',
    ],
    summary: '너와 나의 중간지점',
    githubUrl: 'https://github.com/BoBeenLee/map',
    homeUrl:
      'https://play.google.com/store/apps/details?id=com.nexters.intersection.intersectionapp',
    images: Object.values(portfolioIntersectionImages),
  },
  {
    id: 'competition',
    name: 'Competition',
    period: '',
    githubRepoName: [],
    skills: [
      'bootstrap',
      'angularJS',
      'lessJS',
      'jQuery',
      'spring-framework',
      'tiles',
      'myBatis',
      'mariaDB',
    ],
    summary: 'Sungkonghoe University Competition Site',
    githubUrl: 'https://github.com/BoBeenLee/SkhuCompetition.Server',
    homeUrl: '',
    images: Object.values(portfolioCompetitionImages),
  },
  {
    id: 'softhome',
    name: 'Softhome',
    period: '',
    githubRepoName: [],
    skills: ['jQuery', 'prototypeJs', 'jPagejs', 'jsp', 'myBatis'],
    summary: 'Sungkonghoe University Software Engineering Department Site',
    githubUrl: 'https://github.com/BoBeenLee/swhome',
    homeUrl: '',
    images: Object.values(portfolioSofthomeImages),
  },
];

export type PortfolioItem = Merge<
  MergeArrayType<typeof companyPortfolios>,
  MergeArrayType<typeof teamPortfolios>
>;
