export const portfolioHouseImages = {
  facebook: '/assets/portfolio/house/facebook.png',
  kakao: '/assets/portfolio/house/kakao.png',
  list: '/assets/portfolio/house/list.png',
  login: '/assets/portfolio/house/login.png',
  main: '/assets/portfolio/house/main.png',
  mypage: '/assets/portfolio/house/mypage.png',
  read1: '/assets/portfolio/house/read1.png',
  read2: '/assets/portfolio/house/read2.png',
  setting: '/assets/portfolio/house/setting.png',
  signup: '/assets/portfolio/house/signup.png',
  write1: '/assets/portfolio/house/write1.png',
  write2: '/assets/portfolio/house/write2.png',
  write3: '/assets/portfolio/house/write3.png',
};
