export const portfolioSofthomeImages = {
  softhome1: '/assets/portfolio/softhome/1.png',
  softhome2: '/assets/portfolio/softhome/2.png',
  softhome3: '/assets/portfolio/softhome/3.png',
  softhome4: '/assets/portfolio/softhome/4.png',
  softhome5: '/assets/portfolio/softhome/5.png',
  softhome6: '/assets/portfolio/softhome/6.png',
  softhome7: '/assets/portfolio/softhome/7.png',
  softhome8: '/assets/portfolio/softhome/8.png',
  mailbox: '/assets/portfolio/softhome/mailbox.png',
  main: '/assets/portfolio/softhome/main.png',
  pics: '/assets/portfolio/softhome/pics.png',
  progress: '/assets/portfolio/softhome/progress.png',
  qnabrd: '/assets/portfolio/softhome/qnabrd.png',
  read: '/assets/portfolio/softhome/read.png',
  write: '/assets/portfolio/softhome/write.png',
};
