[build]
  command = "remix build"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "16.13.0"

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

[functions]
  included_files = ["posts/**"]